FROM golang:1.16-alpine AS builder

WORKDIR /app

COPY . .

#COPY ./server/server.go main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/server ./server/server.go

FROM scratch

COPY --from=builder /go/bin/server /go/bin/server
ENTRYPOINT ["/go/bin/server"]
EXPOSE 3032
