FROM golang:1.16-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download


RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /go/bin/client ./client/client.go

FROM scratch

COPY --from=builder /go/bin/client /go/bin/client
ENTRYPOINT ["/go/bin/client"]
